<!-- Added by NI Breadcrumbs Plugin created by Peter Featherstone -->

<div id='ni-breadcrumbs'>

    <span prefix="v: http://rdf.data-vocabulary.org/#">
        
        <?php if( !is_front_page() ) : ?>

            <span typeof="v:Breadcrumb">
                <a property="v:title" 
                   rel="v:url" 
                   class="ni-breadcrumb ni-breadcrumb-first" 
                   href="<?php echo get_home_url(); ?>">
                       <?php echo $data['home']; ?></a>
            </span>
        <?php

        for( $i=0; $i < $data['total-pages']; $i++ ) : 

            $isLast = $data['pages'][$i] != $data['pages'][$data['total-pages'] - 1] ? true : false;

            echo $data['sep'] . ' ';
            echo '<span typeof="v:Breadcrumb">
                    <a property="v:title" rel="v:url" class="ni-breadcrumb" href="' . get_permalink( $data['pages'][$i] ) . '">';

             echo get_the_title( $data['pages'][$i] );

            echo '</a></span> ';

        endfor; ?>

        <?php echo $data['sep']; ?>

        <span typeof="v:Breadcrumb">
            
            <span property="v:title" 
                  class="ni-breadcrumb ni-breadcrumb-last">
                <?php echo $data['current-title']; ?>
            </span>
            
        </span>

        <?php endif; ?>

    </span>
    
</div>

<!-- End added by NI Breadcrumbs Plugin created by Peter Featherstone -->